"""Add service request and service request history models

Revision ID: 20260126_service_request
Revises: 20260125_add_audit_index
Create Date: 2026-01-26 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20260126_service_request'
down_revision = '20260125_add_audit_index'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_request',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['user.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_request_assigned_to'), ['assigned_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_request_created_by'), ['created_by'], unique=False)

    op.create_table('service_request_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_request_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('old_status', sa.String(length=20), nullable=True),
    sa.Column('new_status', sa.String(length=20), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['service_request_id'], ['service_request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_request_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_request_history_service_request_id'), ['service_request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_request_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_request_history_service_request_id'))

    op.drop_table('service_request_history')
    with op.batch_alter_table('service_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_request_assigned_to'))
        batch_op.drop_index(batch_op.f('ix_service_request_created_by'))

    op.drop_table('service_request')
    # ### end Alembic commands ###
