"""Add indices to ServiceRequest for dashboard performance

Revision ID: 20260126_add_indices
Revises: 20260126_service_request
Create Date: 2026-01-26 13:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20260126_add_indices'
down_revision = '20260126_service_request'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_request_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_request_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_request_created_at'), ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_request_created_at'))
        batch_op.drop_index(batch_op.f('ix_service_request_priority'))
        batch_op.drop_index(batch_op.f('ix_service_request_status'))
    # ### end Alembic commands ###
