"""sprint2 models

Revision ID: 43e81b8d02c2
Revises: 43078e9aaada
Create Date: 2026-03-14 18:51:27.621924
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '43e81b8d02c2'
down_revision: Union[str, None] = '43078e9aaada'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
